### ISSUE TITLE
A question about the architecture

### ISSUE THREAD

**Issue by Zhiquan-Wen** [luyao777/HBP-Pytorch#1]
whether need to add another linear transformation after the concatenate the bilinear feature?Because the formulation in the paper is `z=P^T concat(U^T x * V^T y, ...)`

**Comment by luyao777** [comment]
Thanks for your issue. Is the linear transformation you mentioned [here](https://github.com/luyao777/HBP-pytorch/blob/390d6cab65e0a73bfba840d96ad99f69e5c9100c/HBP_fc.py#L88)?
I think`P^T` is fully connected layer to classify the bird.

**Comment by Zhiquan-Wen** [comment]
> Thanks for your issue. Is the linear transformation you mentioned [here](https://github.com/luyao777/HBP-pytorch/blob/390d6cab65e0a73bfba840d96ad99f69e5c9100c/HBP_fc.py#L88)?
> I think`P^T` is fully connected layer to classify the bird.

Yes, you are right, I mistake that formulation. Thank you!
