### ISSUE TITLE
HBP定义中的代码我有点不理解

### ISSUE THREAD

**Issue by roseif** [luyao777/HBP-Pytorch#10]
proj_1 = self.bilinear_proj(conv1)
        proj_2 = self.bilinear_proj(conv2)
        assert(proj_1.size() == (N,8192,28,28))
        X = proj_1 * proj_2
        assert(X.size() == (N,8192,28,28)) 
这里不应该是两个卷积层外积操作吗？出来不应该是[N,8192,8192]吗？为什么是(N,8192,784))

**Comment by jinshistd** [comment]
这个是矩阵的哈达码积，即对应元素相乘，不是矩阵的乘法。

**Comment by luyao777** [comment]
Close due to no response
