### ISSUE TITLE
帅哥  加油啊  早日达到论文精度 我们为你喝彩

### ISSUE THREAD

**Issue by sankin1770** [luyao777/HBP-Pytorch#2]

**Comment by sankin1770** [comment]
N = conv1.size()[0]
        proj_1 = self.bilinear_proj(conv1)
        proj_2 = self.bilinear_proj(conv2)
        assert(proj_1.size() == (N,8192,28,28))
        X = proj_1 * proj_2
看你这里实现是内积   论文里面应该是外积把

**Comment by luyao777** [comment]
谢谢鼓励~:wink:
