### ISSUE TITLE
NameError: name 'options' is not defined

### ISSUE THREAD

**Issue by KelvinHuang666** [luyao777/HBP-Pytorch#7]
------------------------------------------------------------
    main()
  File "HBP_fc.py", line 270, in main
    manager = HBPManager(options, path)
  File "HBP_fc.py", line 94, in __init__
    self._options = options
NameError: name 'options' is not defined

**Comment by luyao777** [comment]
'options' is [here](https://github.com/luyao777/HBP-pytorch/blob/156435ee994e53e79c403917eb24005de8fd8c32/HBP_fc.py#L254).

you may need to debug

**Comment by KelvinHuang666** [comment]
your code error in line 93 : def __init__(self, optins, path):----> def __init__(self, options, path):

**Comment by luyao777** [comment]
Okay, I have fixed that in [79440b4](https://github.com/luyao777/HBP-pytorch/commit/79440b43f4fba704873f0d78250e0a18b1b513d3). Thanks for your suggestion.
