### ISSUE TITLE
  File "/torch_yolov4/HBP-pytorch/cub200.py", line 89, in __init__

### ISSUE THREAD

**Issue by KelvinHuang666** [luyao777/HBP-Pytorch#8]
os.path.join(self._root, 'processed/test.pkl'), 'rb'),encoding='iso-8859-1')
_pickle.UnpicklingError: pickle data was truncated
how can i solve it???thanks

**Comment by luyao777** [comment]
Can you provide more details of the error? Maybe u need to download the dataset from official website.

**Comment by luyao777** [comment]
Closed due to no response.
